package ru.vassuv.blixr.repository.db

const val USER = "User"
const val BP_CONTRACT = "bpContract"
const val ID = "id"

const val FIRST_NAME = "firstName"
const val LAST_NAME = "lastName"
const val EMAIL = "email"
const val ID_NUMBER = "idNumber"
const val CONFIRMED = "confirmed"
const val ODOO_ID = "odoo_id"
const val USER_ID = "userId"
const val UID = "uid"
const val FETCH_URL = "fetch_url"

const val PRODUCT = "product"
const val PICTURES = "pictures"
const val PRODUCT_BRAND = "productBrand"
const val PRODUCT_MODEL = "productModel"
const val PRODUCT_STATE = "productState"
const val PRODUCT_SERIAL = "productSerial"
const val EVENT_NAME = "eventName"
const val EVENT_LOCATION = "eventLocation"
const val EVENT_DATE = "eventDate"
const val NUMBER_OF_TICKETS = "numberOfTickets"
const val CONTRACT_PRICE = "contractPrice"
const val CONTRACT_CAT = "contractCat"
const val CONTRACT_FREE_TEXT = "contractFreeText"
const val CONTRACT_DATE = "contractDate"
const val BUYER = "buyer"
const val SELLER = "seller"
const val CODE = "code"
const val BUYER_SIGNATURE = "buyerSignature"
const val SELLER_SIGNATURE = "sellerSignature"
const val CONTRACT_KEY = "contractKey"
const val DELIVERY_METHOD = "deliveryMethod"
const val DELIVERY_DATE = "deliveryDate"
const val PAYMENT_METHOD = "paymentMethod"
const val SHAONE_SUM = "shaOneSum"
const val BPPAID_STATUS = "bpPaidStatus"
const val NUMBER_OF_PHOTOS = "numberOfPhotos"
const val CONTRACT_TEMPLATE = "contractTemplate"
const val VALID_WARRANTY = "validWarranty"
const val ORIGINAL_RECEIPT = "originalReceipt"